config/routes.rb
Rails.application.routes.draw do
  
 

  root 'pages#Index'
  
  

  get '/home'  => 'pages#Home'

  get '/profile' => 'pages#Profile'

  get '/explore' => 'pages#Explore'
  
  get '/signup' => 'users#new'
  
  get	'/login' 	=>	'sessions#new'

	post	'/login' => 'sessions#create'

	delete '/logout' => 'sessions#destroy'

  
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
    attr_accessor :remember_token
    before_save {self.email = email.downcase }
    validates :fullname, presence: true, length: {maximum: 50}
    VALID_EMAIL_REGEX	=	/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 255},
                        format: {with: VALID_EMAIL_REGEX},
                        uniqueness: {case_sensitive: false}
    has_secure_password
    validates :password, length: {minimum: 6}, allow_blank: true
    
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
    
    def User.new_token
        SecureRandom.urlsafe_base64
    end
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end
    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
    def forget
        update_attribute(:remember_digest, nil)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def Index
  end

  def Home
  end

  def Profile
  end

  def Explore
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def	create
  	user	=	User.find_by(email:	params[:session][:email].downcase)
			if	user	&&	user.authenticate(params[:session][:password])
				log_in user
				params[:session][:remember_me] == '1' ? remember(user) : forget(user)
				redirect_to user
				else
			  flash.now[:danger] = 'Invalid email/password combination'
			  render 'new'
			end
  end

  def destroy
  	log_out if logged_in?
  	redirect_to root_url
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in_user, only: [:edit,:update] 
    before_action :correct_user, only: [:edit, :update]
    
    def show
       @user =	User.find(params[:id])
    end
    
    def new
        @user = User.new
    end
    
    def create
    @user	=	User.new(user_params)
    if	@user.save
        flash[:success]	=	"Welcome to	the	Sample App!"
        redirect_to	 @user
    else
    render 'new'
    end
    end
    
    def edit
        @user = User.find_by_id(params[:id])
    end
    
    def update
        @user =	User.find_by_id(params[:id])
        if	@user.update_attributes(user_params)
        flash[:success]	= "Profile updated"
        redirect_to	@user
        else
        render	'edit'
        end
    end
    
    private
    def user_params
        params.require(:user).permit(:fullname,	:nickname, :email,	:password, :password_confirmation)
    end
    def	logged_in_user
    unless	logged_in?
        flash[:danger]	=	"Please	log	in."
        redirect_to	login_url
    end
    end
    
    def	correct_user
        @user =	User.find_by_id(params[:id])
        redirect_to(root_url) unless @user == current_user
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def log_in(user)
        session[:user_id] = user.id
    end
    
    def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
    end
    
   
    def current_user
        if(user_id = session[:user_id])
            current_user ||=User.find_by(id: session[:user_id])
         elsif user_id = cookies.signed[:user_id]
            user = User.find_by(id: user_id)
            if user && user.authenticated?(cookies[:remember_token])
                log_in user
                @current_user = user
            end
        end
    end
    
    def logged_in?
        !current_user.nil?
    end
   
    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end
    
    def log_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<% unless logged_in? %>
<%= render '/layouts/nav_guest'%>
<% else %>
<%= render '/layouts/nav_user'%>
<% end %>

app/views/layouts/_nav_guest.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">ZombieTwitter</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">Explore</a></li>
        </ul>
      <ul class="nav navbar-nav navbar-right">
          <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Navigation <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Help</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Sign Up', signup_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Sign In', login_path %></li>
            <li role="separator" class="divider"></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_nav_user.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">ZombieTwitter</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/home">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Explore</a></li>
        </ul>
      
      <ul class="nav navbar-nav navbar-right">
          <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
        <li><a href="#">Tweet</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.fullname %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/profile">Profile</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Help</a></li>
            <li role="separator" class="divider"></li>
            <%= link_to 'Edit Profile', edit_user_path(current_user) %></li>
            <li role="separator" class="divider"></li>
            <li> <%= link_to 'Log Out', logout_path, method: :delete %> </li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twittertest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render '/layouts/nav' %>
<div	class="container">
<%	flash.each	do	|message_type,	message|	%>
<div	class="alert	alert-<%=	message_type	%>"><%=	message	%></div>
<%	end	%>
<%= yield %>
<%=	debug(params)	if	Rails.env.development?	%>
</div>
</body>
</html>

app/views/pages/Explore.html.erb
<h1>Pages#Explore</h1>
<p>Find me in app/views/pages/Explore.html.erb</p>

app/views/pages/Home.html.erb
<h1>Pages#Home</h1>
<p>Find me in app/views/pages/Home.html.erb</p>

app/views/pages/Index.html.erb
<h1>Pages#Index</h1>
<p>Find me in app/views/pages/Index.html.erb</p>

app/views/pages/Profile.html.erb
<h1>Pages#Profile</h1>
<p>Find me in app/views/pages/Profile.html.erb</p>

app/views/shared/_error_messages.html.erb
<%	if	@user.errors.any?	%>
<div	id="error_explanation">
<div	class="alert	alert-danger">
The	form	contains	<%=	pluralize(@user.errors.count,	"error")	%>
</div>
<ul>
<%	@user.errors.full_messages.each	do	|msg|	%>
<li><%=	msg	%></li>
<%	end	%>
</ul>
</div>
<%	end	%>

app/views/users/edit.html.erb
<h1>Edit Your profile</h1>
<div class="row">
<div class="col-xs-4 col-xs-offset-4">
<%=	form_for(@user)	do	|f|	%>
    <%=	render	'shared/error_messages',  object: f.object	%>
    <div class="field">
        <%=	f.label	:fullname	%>
        <%=	f.text_field :fullname, class:	'form-control'	%>
    </div>
    <div class="field">
    <%=	f.label	:nickname	%>
    <%=	f.text_field :nickname, class:	'form-control'		%>
    </div>
    <div class="field">
    <%=	f.label	:email	%>
    <%=	f.email_field :email, class:	'form-control'		%>
    </div>
    <div class="field">
    <%=	f.label	:password	%>
    <%=	f.password_field	:password, class:	'form-control'		%>
    </div>
    <div class="field">
    <%=	f.label	:password_confirmation,	"Confirmation"	%>
    <%=	f.password_field	:password_confirmation, class:	'form-control'		%>
    </div>
    <div class="field">
    <%=	f.submit "Save Changes", class: "btn btn-primary" %>
    </div>
<% end %>
</div>
</div>

app/views/users/new.html.erb
<div class="row">
<div class="col-xs-4 col-xs-offset-4">
    <h1>Sign up</h1>
    
<%=	form_for(@user)	do	|f|	%>
<%=	render	'shared/error_messages'	%>
<div class="field">
<%=	f.label	:fullname	%>
<%=	f.text_field :fullname, class:	'form-control'	%>
</div>
<div class="field">
<%=	f.label	:nickname	%>
<%=	f.text_field :nickname, class:	'form-control'		%>
</div>
<div class="field">
<%=	f.label	:email	%>
<%=	f.email_field :email, class:	'form-control'		%>
</div>
<div class="field">
<%=	f.label	:password	%>
<%=	f.password_field	:password, class:	'form-control'		%>
</div>
<div class="field">
<%=	f.label	:password_confirmation,	"Confirmation"	%>
<%=	f.password_field	:password_confirmation, class:	'form-control'		%>
</div>
<div class="field">
<%=	f.submit "Create my	account", class: "btn btn-primary" %>
</div>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<h1><%= @user.fullname %></h1>